services:
  db:
    image: postgres:16
    environment:
      POSTGRES_DB: ${DB_NAME:-warehouse}
      POSTGRES_USER: ${DB_USER:-postgres}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-postgres}
    ports: ["5432:5432"]
    volumes: ["pgdata:/var/lib/postgresql/data"]
volumes:
  pgdata: {}
